### PR TITLE
Paginate all NFTs of a given wallet

### LINKED ISSUE #2: Add an example that paginate all NFTs of a given wallet
Create a simple React application that paginate NFTs from a given wallet.

- **Add an input text** for users to enter the public key of someone's wallet.
- **Use that wallet address** to fetch all of its NFTs using the JS SDK.
- **Paginate these NFTs** in an efficient way. Pagination is not really a think with `getProgramAcccount` so we have to be creative. This article help understand [how to achieve pagination in Solana](https://lorisleiva.com/paginating-and-ordering-accounts-in-solana). This is abstracted by the SDK but we still need to be clever about how we call its method and load the data.
- **Write a detailed README file that explains the steps to reproduce** to achieve the created example. Look at the current READMEs for inspiration. Since this example is not about getting started with a web framework, choose a starting framework from this repository and link to its README as the first first. I recommend Next.js since it has the lowest amount of steps to get started right now.
- When writing the steps to reproduce, it is fine to add links to larger components or style sheets instead of having to explain them all in the README. Especially if the component is more here for UI proposes than for providing valuable logic.
- When styling components, try to stay consistent to the neutral style that was created in the existing examples.

### PR DESCRIPTION
**Pull request by apoorvdwi**
Closes #2 

## What have been done:
- Implemented example for paginating NFTs of a user 's wallet
- Added a descriptive readme explaining the need and implementation details

### CODE REVIEW

File: example-paginate-nfts/pages/index.js [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+  const loadData = async (startIndex, endIndex) => {
+    await nftList.forEach(async (nft, index) => {
+      if (
+        index >= startIndex &&
+        index < endIndex &&
+        nft.metadataTask.isPending()
+      ) {
+        await nft.metadataTask.run();
+      }
+    });
```
Comment (lorisleiva) [inline example-paginate-nfts/pages/index.js:43]: It would be better to load the metadata of all NFTs on the current page in parallel rather than doing it sequentially.

Something like that should work:

```suggestion
    const nftsToLoad = nftList.filter((nft, index) => {
      return (
          index >= startIndex &&
          index < endIndex &&
          nft.metadataTask.isPending()
        );
    });
    
    const promises = nftsToLoad.map(nft => nft.metadataTask.run());
    await Promise.all(promises);
```

**Review by lorisleiva — CHANGES_REQUESTED** [review]
Good job! I've left lots of comments for you to review.

Something else I wanted to comment on: Let's rename that example to `paginate-nfts`. Otherwise, all other examples will have the `example-` prefix.

Also, don't forget to update the main README of the repository with a link to your example.

File: paginate-nfts/README.md [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+      }
+   };
+   ```
+   This sets the `Loading` state to true, invalidates the current view and makes a call to `findAllByOwner` method with wallet address as input.
+
+   The data is set to `nftList` state and current page is set to default 1 (first page).
+
+2. **UseEffect gets Triggered**
+   
+   Once the nftList is in place and currentPage is set to 1, it triggers the useEffect.
```
Comment (lorisleiva) [inline paginate-nfts/README.md:41]:
```suggestion
3. **Load the JSON metadata of every NFT in the current page.**

   We then use a `useEffect` hook to load the NFTs of the current page whenever `nftList` or `currentPage` gets updated.
   
   For instance, when the user provides its wallet address, the `nftList` is updated and `currentPage` is set to 1, which means the `useEffect` hook will be triggered.
```

File: paginate-nfts/README.md [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+   const execute = async () => {
+   const startIndex = (currentPage - 1) * perPage;
+   const endIndex = currentPage * perPage;
+   await loadData(startIndex, endIndex);
+   setCurrentView(nftList.slice(startIndex, endIndex));
+   setLoading(false);
+   };
+   execute();
+   }
+   }, [nftList, currentPage]);
```
Comment (lorisleiva) [inline paginate-nfts/README.md:55]: Fixed bad indentation and returned early so if the nftList is null to make it easier to read. Please make sure this is also updated in the index.js file.

```suggestion
   useEffect(() => {
     if (!nftList) {
       return;
     }
     
     const execute = async () => {
       const startIndex = (currentPage - 1) * perPage;
       const endIndex = currentPage * perPage;
       await loadData(startIndex, endIndex);
       setCurrentView(nftList.slice(startIndex, endIndex));
       setLoading(false);
     };
     
     execute();
   }, [nftList, currentPage]);
```

File: paginate-nfts/README.md [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+        index >= startIndex && index < endIndex && nft.metadataTask.isPending()
+      );
+    });
+
+    const promises = nftsToLoad.map((nft) => nft.metadataTask.run());
+    await Promise.all(promises);
+   };
+   ```
+
+   The index range of NFTs falling in current page is then set to the currentView state and is displayed.
```
Comment (lorisleiva) [inline paginate-nfts/README.md:73]:
```suggestion
   The range of NFTs falling on the current page is then set to the `currentView` state and displayed.
```

File: paginate-nfts/README.md [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+
+3. **If Page is changed**
+   
+   Once the user clicks `Next Page` or `Prev Page`, the useEffect is again triggered, the index range for new page is checked for any NFTs with metadata not loaded and the new view index range is set to current view.
```
Comment (lorisleiva) [inline paginate-nfts/README.md:77]:
```suggestion
4. **What happens when the page changes?**
   
   Whenever the user clicks the "Next Page" or "Prev Page" button, the `useEffect` hook is again triggered. That means, it will load the JSON metadata for any NFT within that index range that isn't already loaded and display them to the current view.
```

File: paginate-nfts/README.md [hunk 6]
```diff
@@ -0,0 +1,90 @@
...
+
+4. **If Fetch button is clicked again**
+   
+   If the user clicks Fetch button with a different wallet address or with same wallet address to get a refreshed list of NFTs, the process repeats from step 1.
+
+Let's see the final output 🥳
```
Comment (lorisleiva) [inline paginate-nfts/README.md:83]: No need for explaining this since we've already explained it in step 3. Instead, let's replace it with the final congrats step.

```suggestion
5. **That's it!** 🎉
   
   Congrats, you've now got a simple app that displays the NFTs inside a wallet. Let's see the final output!
```

File: paginate-nfts/pages/index.js [hunk 7]
```diff
@@ -0,0 +1,123 @@
...
+    if (nftList) {
+      const execute = async () => {
+        const startIndex = (currentPage - 1) * perPage;
+        const endIndex = currentPage * perPage;
+        await loadData(startIndex, endIndex);
+        setCurrentView(nftList.slice(startIndex, endIndex));
+        setLoading(false);
+      };
+      execute();
+    }
```
Comment (lorisleiva) [inline paginate-nfts/pages/index.js:31]: See my comment above in the README.

File: paginate-nfts/pages/index.js [hunk 8]
```diff
@@ -0,0 +1,123 @@
...
+      return (
+        index >= startIndex && index < endIndex && nft.metadataTask.isPending()
+      );
+    });
+
+    const promises = nftsToLoad.map((nft) => nft.metadataTask.run());
+    await Promise.all(promises);
+  };
+
+  const fetchNFTs = async () => {
```
Comment (lorisleiva) [inline paginate-nfts/pages/index.js:45]: Could we move the `fetchNFTs` function above the useEffect hook? That way it reads in the same order as the tutorial.

**Review by lorisleiva — CHANGES_REQUESTED** [review]
Great job! We're almost there. I've left lots of comments on the README with many suggestions that you can just click to commit. I wanted to do that so you can learn from these changes and see how they convey information to the reader in a clearer way. I hope this helps.

**Comment by apoorvdwi** [comment]
Thanks for the feedback !! I have included all the changes mentioned above in my PR

File: paginate-nfts/README.md [hunk 9]
```diff
@@ -0,0 +1,96 @@
...
+
+![image](https://user-images.githubusercontent.com/56197821/176737427-43df0aca-6ea9-443f-b9e9-718bdb654ab4.png)
+
+Okay, let's get started! 🔥
+
+Note that you can find all the code below in this [`pages/index.js` file](./pages/index.js).
+
+1. **Create a new Next.js app.**
+   
+   We will be using the [findAllByOwner](https://github.com/metaplex-foundation/js#findallbyowner) method in the Metaplex SDK which will give us the list of NFTs without their JSON metadata loaded. This is important because if we had to fetch hundreds of NFTs with their JSON metadata, it will take a lot of time and greatly impact the performance of the application.
```
Comment (lorisleiva) [inline paginate-nfts/README.md:18]: This sentence should have been left in the intro. It does not affect the Next.js step. Please move it back between the first and the second paragraph of the into.

**Review by lorisleiva — CHANGES_REQUESTED** [review]
Nice! Just a tiny tweak and we can merge this. 🙂

**Review by lorisleiva — APPROVED** [review]
